// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Database URLs live in .env.local (they are credentials); .env holds non-secret config.
// Load .env.local first so it wins for duplicate names — the same precedence Next uses.
dotenv.config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations want the direct connection: Prisma's engine takes advisory locks and runs DDL,
    // which a transaction-mode pooler can break. The pooled URL is only a fallback here.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
